name: network_editor_example

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  tabler_icons_plus: ^3.41.0
  flutter_lints: ^6.0.0
  network_editor:
    path: ../
  flutter_svg: ^2.2.4
  geolocator: ^14.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/